name: Build MangosSharp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Path: ./Source/Mangos.sln
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore $env:Solution_Path

    - name: Build
      run: dotnet build --no-restore $env:Solution_Path

    - name: Test
      run: dotnet test --no-restore $env:Solution_Path

    - name: Verify
      run: dotnet format --verify-no-changes --no-restore $env:Solution_Path